"""Add Share table with image URL

Revision ID: c475abb4f249
Revises: f495be8c19f7
Create Date: 2025-02-17 14:19:28.915628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c475abb4f249'
down_revision: Union[str, None] = 'f495be8c19f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('image_url', sa.String(), nullable=False))
    op.add_column('shares', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('shares', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_shares_share_link'), 'shares', ['share_link'], unique=True)
    op.drop_column('shares', 'shared_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('shared_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_shares_share_link'), table_name='shares')
    op.alter_column('shares', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('shares', 'created_at')
    op.drop_column('shares', 'image_url')
    # ### end Alembic commands ###
