"""Create collab_canvas table

Revision ID: 015e17017f4c
Revises: 399550adcf0c
Create Date: 2025-03-03 21:13:02.627774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015e17017f4c'
down_revision: Union[str, None] = '399550adcf0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collab_canvas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_data', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collab_canvas_id'), 'collab_canvas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collab_canvas_id'), table_name='collab_canvas')
    op.drop_table('collab_canvas')
    # ### end Alembic commands ###
