"""Add user_id and created_at to History

Revision ID: 204595521c1a
Revises: a00da0fb0a30
Create Date: 2025-03-06 22:57:40.051232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204595521c1a'
down_revision: Union[str, None] = 'a00da0fb0a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
