"""Add user_id to History

Revision ID: 52ca415d24c9
Revises: 204595521c1a
Create Date: 2025-03-06 23:24:32.803711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ca415d24c9'
down_revision: Union[str, None] = '204595521c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('user_id', sa.Integer(), nullable=False, server_default="1"))
    op.create_foreign_key(None, 'history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_column('history', 'user_id')
    # ### end Alembic commands ###
