"""Create Share Table

Revision ID: 7b352bd4f794
Revises: 2c43b4350501
Create Date: 2025-02-17 13:55:20.493910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b352bd4f794'
down_revision: Union[str, None] = '2c43b4350501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=True),
    sa.Column('share_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shares_id'), 'shares', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shares_id'), table_name='shares')
    op.drop_table('shares')
    # ### end Alembic commands ###
