"""Add created_at field to History model

Revision ID: a00da0fb0a30
Revises: 015e17017f4c
Create Date: 2025-03-06 22:55:36.903310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00da0fb0a30'
down_revision: Union[str, None] = '015e17017f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'created_at')
    # ### end Alembic commands ###
