"""Set default value for created_at in History

Revision ID: c315471e0936
Revises: d65bb568176a
Create Date: 2025-03-06 23:53:58.162887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c315471e0936'
down_revision: Union[str, None] = 'd65bb568176a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
